# Generated by Django 2.2.5 on 2019-11-26 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20171216_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='imageUrl',
            field=models.CharField(blank=True, default='', help_text='Add thumbnail image to the trip', max_length=300),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cost',
            field=models.IntegerField(help_text='Total cost of the trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(help_text='Initial location of the trip', max_length=300),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration_days',
            field=models.IntegerField(help_text='How many days this trip runs'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='title',
            field=models.CharField(help_text='The name of the trip', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_style',
            field=models.CharField(help_text='The type of G Adventures trip', max_length=300),
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('typeOfService', models.TextField(default='transportation', help_text='The name of the service, e.g. hotel, accomodation or transportation', max_length=64)),
                ('location', models.CharField(default='', max_length=100)),
                ('cost', models.IntegerField(help_text='Total cost of the trip')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('typeOfService', models.TextField(help_text='The name of the service, e.g. hotel, accomodation or transportation', max_length=64)),
                ('location', models.CharField(max_length=100)),
                ('cost', models.IntegerField(help_text='Total cost of the trip')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('typeOfService', models.TextField(default='accomodation', help_text='The name of the service, e.g. hotel, accomodation or transportation', max_length=64)),
                ('location', models.CharField(max_length=100)),
                ('cost', models.IntegerField(help_text='Total cost of the trip')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip')),
            ],
        ),
    ]
