# Generated by Django 2.2.5 on 2019-10-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20171216_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the hotel', max_length=300, unique=True)),
                ('type', models.CharField(help_text='The type of G Adventures hotel', max_length=300)),
                ('location', models.CharField(help_text='Location of the hotel', max_length=300)),
                ('cost', models.IntegerField(help_text='Total cost of the hotel')),
            ],
        ),
        migrations.AlterField(
            model_name='trip',
            name='cost',
            field=models.IntegerField(help_text='Total cost of the trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(help_text='Initial location of the trip', max_length=300),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration_days',
            field=models.IntegerField(help_text='How many days this trip runs'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='title',
            field=models.CharField(help_text='The name of the trip', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_style',
            field=models.CharField(help_text='The type of G Adventures trip', max_length=300),
        ),
    ]
