# Generated by Django 2.2.5 on 2019-11-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20171216_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='accomodation',
            field=models.CharField(blank=True, default='', help_text='Add other types of accomodation', max_length=300),
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel',
            field=models.CharField(blank=True, default='', help_text='Add Hotel', max_length=300),
        ),
        migrations.AddField(
            model_name='trip',
            name='transportation',
            field=models.CharField(blank=True, default='', help_text='Add transportation method', max_length=300),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cost',
            field=models.IntegerField(help_text='Total cost of the trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(help_text='Initial location of the trip', max_length=300),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration_days',
            field=models.IntegerField(help_text='How many days this trip runs'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='title',
            field=models.CharField(help_text='The name of the trip', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_style',
            field=models.CharField(help_text='The type of G Adventures trip', max_length=300),
        ),
    ]
