# Generated by Django 2.2.5 on 2019-11-30 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20171216_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='the name of the service category', max_length=300, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='trip',
            name='cost',
            field=models.IntegerField(help_text='Total cost of the trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(help_text='Initial location of the trip', max_length=300),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration_days',
            field=models.IntegerField(help_text='How many days this trip runs'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='title',
            field=models.CharField(help_text='The name of the trip', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_style',
            field=models.CharField(help_text='The type of G Adventures trip', max_length=300),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name of the trip', max_length=300, unique=True)),
                ('location', models.CharField(help_text='the location of the trip as an address', max_length=300)),
                ('cost', models.IntegerField(help_text='The cost of the service')),
                ('category', models.ForeignKey(help_text=' reference of what category of service this is', on_delete=django.db.models.deletion.CASCADE, to='trips.Category')),
                ('trip', models.ForeignKey(help_text='reference to the trip this service belongs to', on_delete=django.db.models.deletion.CASCADE, to='trips.Trip')),
            ],
        ),
    ]
