# Generated by Django 2.2.5 on 2019-11-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20191121_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='imageUrl',
            field=models.CharField(blank=True, default='', help_text='Add thumbnail image to the trip', max_length=300),
        ),
    ]
