# Generated by Django 2.2.5 on 2019-11-23 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20191123_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='services',
        ),
        migrations.AddField(
            model_name='service',
            name='trip_id',
            field=models.ForeignKey(help_text='The trip associated to this service', null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.Trip'),
        ),
    ]
