# Generated by Django 2.2.5 on 2019-11-30 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20191130_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(help_text=' reference of what category of service this is', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='trips.Category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='trip',
            field=models.ForeignKey(help_text='reference to the trip this service belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='trips.Trip'),
        ),
    ]
