# Generated by Django 2.2.5 on 2019-10-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20191027_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='trips',
            field=models.ManyToManyField(to='trips.Trip'),
        ),
    ]
