# Generated by Django 2.2.5 on 2019-11-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20191128_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='duration_days',
            field=models.IntegerField(default=0, help_text='How many days this trip runs'),
        ),
    ]
