# Generated by Django 2.2.5 on 2019-12-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20191202_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='trip',
            field=models.ForeignKey(help_text='The trip the service belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.Trip'),
        ),
    ]
