# Generated by Django 2.2.5 on 2019-12-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_service_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='trip',
            new_name='trip_id',
        ),
    ]
