# Generated by Django 2.2.5 on 2019-10-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_hotel_trips'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('title',)},
        ),
    ]
