# Generated by Django 2.2.5 on 2019-11-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20191123_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='trip_id',
            new_name='trip',
        ),
    ]
