# Generated by Django 2.2.5 on 2019-12-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20191130_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display_name',
            field=models.CharField(help_text='the name of the service category', max_length=300),
        ),
    ]
