# Generated by Django 2.2.5 on 2019-11-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20191128_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the hotel', max_length=300, unique=True)),
                ('type', models.CharField(help_text='Type', max_length=300)),
                ('location', models.CharField(help_text='Location of the hotel', max_length=300)),
                ('cost', models.IntegerField(help_text='Total cost of the hotel')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the transportation', max_length=300, unique=True)),
                ('type', models.CharField(help_text='Type', max_length=300)),
                ('location', models.CharField(help_text='Location', max_length=300)),
                ('cost', models.IntegerField(help_text='Total cost of the transportation')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration_days',
            field=models.IntegerField(help_text='How many days this trip runs'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.AddField(
            model_name='trip',
            name='hotels',
            field=models.ManyToManyField(to='trips.Hotel'),
        ),
        migrations.AddField(
            model_name='trip',
            name='transportation',
            field=models.ManyToManyField(to='trips.Transportation'),
        ),
    ]
