# Generated by Django 2.2.5 on 2019-11-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20191128_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='transportation',
            new_name='transportations',
        ),
    ]
