# Generated by Django 2.2.5 on 2019-12-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20191201_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image_url',
            field=models.CharField(help_text='Image of the location of the trip', max_length=300, null=True),
        ),
    ]
