# Generated by Django 2.2.5 on 2019-10-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20191027_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='trips',
        ),
        migrations.AddField(
            model_name='trip',
            name='hotels',
            field=models.ManyToManyField(to='trips.Hotel'),
        ),
    ]
