# Generated by Django 2.2.5 on 2019-11-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20191123_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.IntegerField(choices=[(1, 'Hotel'), (2, 'Accommodations'), (3, 'Transportation')], help_text='The type of service'),
        ),
    ]
