# Generated by Django 2.2.5 on 2019-11-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_auto_20191128_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='hotels',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='transportations',
            new_name='transportation',
        ),
    ]
