# Generated by Django 2.2.5 on 2019-12-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_trip_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='the name of the trip', max_length=300),
        ),
    ]
