# Generated by Django 2.2.5 on 2019-12-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_auto_20191202_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='trip_id',
        ),
        migrations.AddField(
            model_name='service',
            name='trips',
            field=models.ManyToManyField(to='trips.Trip'),
        ),
    ]
