# Generated by Django 2.2.5 on 2019-10-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_auto_20191027_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the transportation', max_length=300, unique=True)),
                ('type', models.CharField(help_text='Type', max_length=300)),
                ('location', models.CharField(help_text='Location', max_length=300)),
                ('cost', models.IntegerField(help_text='Total cost of the transportation')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='hotel',
            name='type',
            field=models.CharField(help_text='Type', max_length=300),
        ),
        migrations.AddField(
            model_name='trip',
            name='transportation',
            field=models.ManyToManyField(to='trips.Transportation'),
        ),
    ]
