# Generated by Django 2.2.5 on 2019-12-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_auto_20191129_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of the trip', max_length=300, unique=True)),
                ('travel_style', models.CharField(help_text='The type of G Adventures trip', max_length=300)),
                ('destination', models.CharField(help_text='Initial location of the trip', max_length=300)),
                ('cost', models.IntegerField(help_text='Total cost of the trip')),
                ('duration_days', models.IntegerField(help_text='How many days this trip runs')),
                ('hotelName', models.CharField(max_length=300)),
                ('hotelCheckIn', models.CharField(max_length=300)),
                ('hotelCheckOut', models.CharField(max_length=300)),
                ('hotelCost', models.CharField(max_length=300)),
                ('transportationType', models.CharField(max_length=300)),
                ('transportationCost', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
