# Generated by Django 2.2.5 on 2019-12-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_auto_20191202_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='trips',
        ),
        migrations.AddField(
            model_name='trip',
            name='services',
            field=models.ManyToManyField(to='trips.Service'),
        ),
    ]
