# Generated by Django 2.2.5 on 2019-12-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_selectedtrip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectedtrip',
            options={},
        ),
        migrations.AlterField(
            model_name='selectedtrip',
            name='cost',
            field=models.IntegerField(blank=True, help_text='Total cost of the trip', null=True),
        ),
        migrations.AlterField(
            model_name='selectedtrip',
            name='destination',
            field=models.CharField(blank=True, help_text='Initial location of the trip', max_length=300),
        ),
        migrations.AlterField(
            model_name='selectedtrip',
            name='duration_days',
            field=models.IntegerField(blank=True, help_text='How many days this trip runs'),
        ),
        migrations.AlterField(
            model_name='selectedtrip',
            name='hotelCheckIn',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='selectedtrip',
            name='hotelCheckOut',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='selectedtrip',
            name='hotelCost',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='selectedtrip',
            name='hotelName',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='selectedtrip',
            name='title',
            field=models.CharField(blank=True, help_text='The name of the trip', max_length=300),
        ),
        migrations.AlterField(
            model_name='selectedtrip',
            name='transportationCost',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='selectedtrip',
            name='transportationType',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='selectedtrip',
            name='travel_style',
            field=models.CharField(blank=True, help_text='The type of G Adventures trip', max_length=300),
        ),
    ]
