# Generated by Django 2.2.5 on 2019-12-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_auto_20191206_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedtrip',
            name='duration_days',
            field=models.IntegerField(blank=True, help_text='How many days this trip runs', null=True),
        ),
    ]
