# Generated by Django 2.2.5 on 2019-12-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_auto_20191206_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedtrip',
            name='cost',
            field=models.CharField(blank=True, help_text='Total cost of the trip', max_length=300),
        ),
        migrations.AlterField(
            model_name='selectedtrip',
            name='duration_days',
            field=models.CharField(blank=True, help_text='How many days this trip runs', max_length=300),
        ),
    ]
