# Generated by Django 2.2.5 on 2019-12-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_auto_20191207_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedtrip',
            name='totalhoteldays',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
