# Generated by Django 2.2.5 on 2019-12-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_selectedtrip_totalhoteldays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedtrip',
            old_name='totalhoteldays',
            new_name='totalHotelDays',
        ),
        migrations.AddField(
            model_name='selectedtrip',
            name='totalhotelCost',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
