# Generated by Django 2.2.5 on 2019-12-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_auto_20191207_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedtrip',
            name='total',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
